### ISSUE TITLE
Issue with `setPin`

### ISSUE THREAD

**Issue by RodionMun** [jonkwheeler/ScrollScene#1]
Hello! First things first, thank you for your work. I am new with gsap and scrollMagic. I need to implement some horizontal scrollable slides in my project. I follow the official tutorial http://scrollmagic.io/examples/advanced/section_slides_manual.html

But it doesn't work. I tried to use `setPin` with your library, as you described.

      import { ScrollMagic, ScrollScene } from 'scrollscene'
      import { gsap } from 'gsap/all'

      export default {
        mounted() {
          const controller = new ScrollMagic.Controller();

          const wipeAnimation = gsap.timeline()
              // animate to second panel
          wipeAnimation.to("#slideContainer", 0.5, {z: -150})		// move back in 3D space
          wipeAnimation.to("#slideContainer", 1,   {x: "-25%"})	// move in to first panel
          wipeAnimation.to("#slideContainer", 0.5, {z: 0})				// move back to origin in 3D space
              // animate to third panel
          wipeAnimation.to("#slideContainer", 0.5, {z: -150, delay: 1})
          wipeAnimation.to("#slideContainer", 1,   {x: "-50%"})
          wipeAnimation.to("#slideContainer", 0.5, {z: 0})
              // animate to forth panel
          wipeAnimation.to("#slideContainer", 0.5, {z: -150, delay: 1})
          wipeAnimation.to("#slideContainer", 1,   {x: "-75%"})
          wipeAnimation.to("#slideContainer", 0.5, {z: 0});

          new ScrollScene({
              triggerElement: "#third-screen",
              triggerHook: "onLeave",
              duration: "500%",
              gsap: {
                  timeline: wipeAnimation
              }
          })

          new ScrollMagic.Scene({
              triggerElement: "#third-screen",
              triggerHook: "onLeave",
              duration: "500%",
          }).setPin("#third-screen")
              .addTo(controller);
        }
      }

It's clear to me that I doing something wrong, but I don't know what.

**Comment by jonkwheeler** [comment]
@RodionMun let's try a couple of things first...

- I added a `$thirdScreen` querySelector. This library doesn't support jQuery or strings as selectors (yet, maybe I'll add that, but it's better if I don't).
- And another for the `$slideContainer`. You were called a `document.querySelector` function each time to find that element, which is expensive and slow. Just call it once.
- I paused the gsap.timeline
- I cleaned up the timeline
- I fixed the gsap import. You should be using `import { gsap } from 'gsap'`
- I fixed the duration on the timeline. You were using Gsap2 syntax. You should be using Gsap3 syntax.
- I created variables for the new Scenes.

Beyond trying the above, it looks like you're applying 2 scenes to the same element. This might cause issues because when you animate that element, your scene triggers are going to change.

```
import { ScrollMagic, ScrollScene } from 'scrollscene'
import { gsap } from 'gsap'

export default {
  mounted() {
    const $thirdScreen = document.querySelector('#third-screen')
    const $slideContainer = document.querySelector('#slideContainer')

    const wipeAnimation = gsap.timeline({ paused: true })
    // animate to second panel
    wipeAnimation
      .to($slideContainer, { duration: 0.5, z: -150 }) // move back in 3D space
      .to($slideContainer, { duration: 1, x: '-25%' }) // move in to first panel
      .to($slideContainer, { duration: 0.5, z: 0 }) // move back to origin in 3D space
      // animate to third panel
      .to($slideContainer, { duration: 0.5, z: -150, delay: 1 })
      .to($slideContainer, { duration: 1, x: '-50%' })
      .to($slideContainer, { duration: 0.5, z: 0 })
      // animate to forth panel
      .to($slideContainer, { duration: 0.5, z: -150, delay: 1 })
      .to($slideContainer, { duration: 1, x: '-75%' })
      .to($slideContainer, { duration: 0.5, z: 0 })

    const myFirstScene = new ScrollScene({
      triggerElement: $thirdScreen,
      triggerHook: 'onLeave',
      duration: '500%',
      gsap: {
        timeline: wipeAnimation,
      },
    })

    const controller = new ScrollMagic.Controller()

    const mySecondScene = new ScrollMagic.Scene({
      triggerElement: $thirdScreen,
      triggerHook: 'onLeave',
      duration: '500%',
    })
      .setPin($thirdScreen)
      .addTo(controller)
  },
}
```

Also, are you using React? If you are, I provided a `React.useEffect` example. Only asking because of the `mounted()` syntax.

Even with these changes, Your dom structure for the `setPin` has to be set up perfectly. I recommend if you're new to ScrollMagic, that you run through Petr's course on [ScrollMagic 101](https://ihatetomatoes.net/get-scrollmagic-101/). It's great and it'll cover the bases you need for Pinning.

**Comment by jonkwheeler** [comment]
I updated this. You need to apply `setPin` to the new `Scene` which I've given you access to... like 

```
const mySecondScene = new ScrollMagic.Scene({...})

mySecondScene.Scene.setPin(...)
```

You can also mess with the controller more now. See the README updates.
